version: "3.3"
services:
  fact-finder:
    image: duongtomho/factfinder:v1.0.0
    restart: always
    ports:
      - "8080"
    # volumes:
    #   - ./../catfacts-fact-finder:/app
    # env_file:
    #   - ./../catfacts-fact-finder/config/config.env
    environment:
      FINDFACT_OFFLINE: "false"

  quote-handler:
    image: duongtomho/catquote:v1.0.0
    depends_on:
      - fact-finder
    restart: always
    ports:
      - "8050:8050"
    # volumes:
    #   - ./../catfacts-quote:/app
    # env_file: 
    #   - ./../catfacts-quote/config/config.env
    environment:
      FACT_FINDER_HOST: fact-finder
